# Copyright 2026 Santos C. Borom
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
########################################################################
"""
mqeintegralloader.py — MQE Pipeline Integral Initialisation
============================================================
Single entry point for bootstrapping an IntegralState at the start of
an MQE pipeline run.

Two loading paths
-----------------
dataset mode  (dataset_dir provided)
    Returns an empty IntegralState with dataset_mode=True.
    StepwiseIntegralStore loads the per-step Hamiltonian H_n at runtime
    from <dataset_dir>/<mechanism>/step_{n:02d}.json.
    Per-step FCI reference energies come from the same JSON files
    (generated by mqedatagenerator.py).  No upfront PySCF call needed.

fallback mode  (dataset_dir is None)
    Generates a minimal synthetic 4-orbital Hamiltonian via
    _generate_fallback_hamiltonian() and computes the exact FCI
    reference energy with PySCF.  Used for development and testing
    when no UFC dataset has been generated yet.

Dependencies
------------
    molecular/mqeintegralstore  — _generate_fallback_hamiltonian
    simulate/mqeconfig          — IntegralState
    pyscf.fci                   — FCI solver (fallback path only)
    numpy
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, Optional, Tuple, Union

import numpy as np
from pyscf import fci

from nanoprotogeny.molecular.mqeintegralstore import _generate_fallback_hamiltonian
from nanoprotogeny.simulate.mqeconfig import IntegralState

log = logging.getLogger(__name__)


def initialise_integrals(
    dataset_dir: Optional[Union[str, Path]] = None,
) -> IntegralState:
    """Bootstrap an IntegralState for the MQE pipeline.

    Safe to call multiple times; each call returns a fresh IntegralState
    with no module-level side-effects.

    Args:
        dataset_dir: Path to the root UFC dataset directory produced by
                     ``mqe generate-data``.  When provided, dataset mode
                     is activated and StepwiseIntegralStore populates
                     H_n per step at runtime.  When None, a synthetic
                     fallback Hamiltonian is used (development/testing).

    Returns:
        Populated IntegralState.
    """
    # ── Dataset mode ─────────────────��─────────────────────────��──────────────
    if dataset_dir is not None:
        log.info(
            "[DATASET MODE] IntegralState initialised empty. "
            "StepwiseIntegralStore will load H_n per step at runtime."
        )
        return IntegralState(
            meta         = {"ncas": 4, "nelec_active": 4, "nalpha": 2,
                            "nbeta": 2, "mol_name": "dataset_mode"},
            dataset_mode = True,
        )

    # ── Fallback mode — synthetic test Hamiltonian ──────────────────────────���─
    log.info("[FALLBACK] No dataset_dir supplied. Using synthetic 4-orbital Hamiltonian.")
    _, h_diag, h_hop, g_full, g_coul, e_core, meta = _generate_fallback_hamiltonian()

    n_orbitals = meta.get("ncas", 4)
    nalpha     = meta.get("nalpha", n_orbitals // 2)
    nbeta      = meta.get("nbeta",  n_orbitals // 2)

    log.info(
        f"[LOADED] Integrals: {len(h_diag)} Diag, {len(h_hop)} Hop, "
        f"{len(g_full)} ERI, Ecore = {e_core:.4f} Ha"
    )
    log.info(
        f"[LOADED] Molecule: {meta.get('mol_name', 'N/A')} "
        f"CAS({meta.get('nelec_active', n_orbitals)},{n_orbitals})"
    )

    # Build dense h1 and ERI tensors for PySCF FCI
    n        = n_orbitals
    h1_full  = np.zeros((n, n), dtype=float)
    for p in range(n):
        h1_full[p, p] = h_diag.get(p, 0.0)
    for (p, q), v in h_hop.items():
        h1_full[p, q] = h1_full[q, p] = float(v)

    eri_full = np.zeros((n, n, n, n), dtype=float)
    for (p, q, r, s), v in g_full.items():
        v = float(v)
        for a, b, c, d in [
            (p,q,r,s),(q,p,s,r),(r,s,p,q),(s,r,q,p),
            (p,q,s,r),(q,p,r,s),(r,s,q,p),(s,r,p,q),
        ]:
            eri_full[a, b, c, d] = v

    # FCI reference energy — QPE checkpoints validate against this
    if h_diag or h_hop or g_full:
        E_fci, _ = fci.direct_spin1.kernel(
            h1_full, eri_full, n, (nalpha, nbeta), ecore=0.0, verbose=0
        )
        log.info(f"[FCI REF] Spin sector: nα={nalpha}, nβ={nbeta}")
        log.info(f"[FCI REF] Active-space energy:  {E_fci:.10f} Ha")
        log.info(f"[FCI REF] Absolute energy (+core): {E_fci + e_core:.10f} Ha")
    else:
        E_fci = 0.0
        log.warning("[FCI REF] Empty integrals — placeholder E_FCI = 0.0 Ha")

    return IntegralState(
        h_diag        = h_diag,
        h_hop         = h_hop,
        g_full        = g_full,
        g_coul        = g_coul,
        e_core        = e_core,
        n_orbitals    = n_orbitals,
        meta          = meta,
        fci_reference = {
            "h1": h1_full, "eri": eri_full,
            "nalpha": nalpha, "nbeta": nbeta,
            "E_active": E_fci, "E_absolute": E_fci + e_core,
        },
        dataset_mode  = False,
    )
